### ISSUE TITLE
schedule first meeting post Node+JS Interactive

### ISSUE THREAD

**Issue by boneskull** [nodejs/tooling#1]
Let's schedule a call in which we can talk about our current initiatives w/ other agenda items as necessary.  Maybe every two weeks?

My best times are generally during typical working hours, with peak availability around noon.  Evenings are off-limits for the next 6 weeks or so.  My TZ is UTC-7.

cc @nodejs/tooling

**Comment by refack** [comment]
I'm good whenever... (I'm at UTC-4)
Best to check the node calendar https://nodejs.org/calendar for clashes. Possibly get a recurring meeting on it as well.

**Comment by mcollina** [comment]
Should we do a doodle?

**Comment by boneskull** [comment]
@mcollina Yes, I think so.  please doodle us

**Comment by ProfNandaa** [comment]
@mcollina -- do we have the next meeting scheduled?

**Comment by boneskull** [comment]
Hey everybody @bcoe, @iansu, @guybedford, @oludiro, @ErickWendel, @ruyadorno, @MichelLopez, @bengl, @mcollina, @nodejs/tooling

**Let's schedule a meeting!**  I'm not sure the best way to do this, but if everyone could give some general availability guidelines, I'll create a doodle.

I'm looking at next week, and am flexible.  I'm UTC-8

**Comment by boneskull** [comment]
cc @ljharb @refack if interested

**Comment by profnandaa** [comment]
I'll work around the works with most, I'm far east on UTC+3 but no worries.

**Comment by ErickWendel** [comment]
Awesome! I'm UTC-2, but no worries too

**Comment by refack** [comment]
> but if everyone could give some general availability guidelines

I'm in EST so 2:00PM-2:00AM UTC (a.k. 9AM-9PM EST a.k. 6AM - 6PM PST) is great by me. But with my insomnia I'm not objecting to anytime ;)

**Comment by guybedford** [comment]
Nice to see this. Perhaps it's worth posting up a Doodle here to find when works for everyone more easily?

I'm available 10am - 10pm UTC next week except for Wednesday and Thursday.

**Comment by iansu** [comment]
I'm UTC-7 and my schedule is pretty flexible. Looking forward to meeting again!

**Comment by boneskull** [comment]
I'll see if I can dig out email addresses from the GitHub profiles from those who have responded, and set up a "doodle".

**Comment by ruyadorno** [comment]
@boneskull please send it my way too 😊

**Comment by refack** [comment]
> I'll see if I can dig out email addresses

core Collaborators are listed at https://github.com/nodejs/node#collaborators

**Comment by boneskull** [comment]
I've sent emails to the best of my ability, but if you didn't get one and you want to meet, just [go to this Doodle](https://doodle.com/poll/wrtgyprvd3aws56c) and put in your preference.

**Comment by boneskull** [comment]
Alright, it looks like Tuesday December 4 at 11a PDT (UTC-8) is what we're going to go with.  I'll see about announcing this more formally.
