### ISSUE TITLE
meeting cadence should be offset by 1 week

### ISSUE THREAD

**Issue by boneskull** [nodejs/tooling#10]
Our current meeting cadence [conflicts with the benchmarking WG's meeting](https://nodejs.org/calendar),  which means we won't be able to stream on YouTube and may force some attendees into an awkward decision.  :smile:

However, I think our next meeting *should* stay on December 18, because the following Tuesday is a holiday.

Thereafter, I propose we offset the meeting schedule by one week to avoid further conflicts.  So the next meeting after December 18 would be January 8.

Sound OK?

@nodejs/tooling

**Comment by boneskull** [comment]
OK, so it appears the benchmarking WG meets every three weeks, so if we want that time slot we too will need to meet every *n* weeks where `n mod 3 == 0` 😄

**Comment by ljharb** [comment]
I’m still not clear on why “one at a time” is a constraint, can’t we pay YouTube or something for the ability to do two streams at a time?

**Comment by boneskull** [comment]
@ljharb You're barking up the wrong tree.  Maybe @mhdawson knows, or could point us to somebody who would.

**Comment by boneskull** [comment]
fine for now
