### ISSUE TITLE
Move meeting time?

### ISSUE THREAD

**Issue by joesepi** [nodejs/tooling#105]
We discussed in today's meeting (and in previous meetings) about moving this meeting to a different time slot.

What was suggested at the beginning of today's meeting is to move it from 4pm ET to 1pm ET. I would try to do the UTC time, but with recent daylight savings time adjustments, that might not be safe. :)

**Comment by bcoe** [comment]
I'm up for that new meeting time.

**Comment by joesepi** [comment]
We discussed and decided to just leave things be. If anyone in the future does want to propose a different time, the team is open to it.
