### ISSUE TITLE
Sort out tooling team member list and maintainer

### ISSUE THREAD

**Issue by joesepi** [nodejs/tooling#106]
https://github.com/orgs/nodejs/teams/tooling/members

Darcy and I could be added to the team. @boneskull is the only maintainer, perhaps that should be updated as well.

**Comment by joesepi** [comment]
@bnb @mhdawson can you make @bcoe, @ruyadorno, @iansu and me (@joesepi) maintainers of the @nodejs/tooling list? Thank you!!

**Comment by mhdawson** [comment]
@joesepi done.

**Comment by bnb** [comment]
If this is done, going to close. Feel free to reopen if there's something still missing.
