### ISSUE TITLE
Feedback on TC39

### ISSUE THREAD

**Issue by littledan** [nodejs/tooling#11]
Hi, apologies for being slightly off-topic, but I am trying to get more feedback for TC39, the JavaScript standards committee. I see JavaScript build tools and transpilers as a really important constituency to involve in our feature development.

For that purpose, I have been arranging some calls to discuss relevant issues. See https://github.com/littledan/js-outreach-groups for some information about existing calls. We're talking about one for Node in https://github.com/nodejs/open-standards/issues/14 , and you are all welcome to join that if you are interested.

But, I think build tools will have somewhat different focuses and concerns than Node general, e.g., thinking through how to down-level various constructs, do code transformations, use modules differently, etc. So I wanted to be especially sure that this group had a separate way to give input. Should we consider having a different call, or some other way of being in touch?

If you have any questions about getting involved in TC39, please feel free to ask in this thread, or DM me on Twitter @littledan, or email at littledan@igalia.com.

Cc @codehag @bterlson

**Comment by littledan** [comment]
That would be great! When is it?

**Comment by iansu** [comment]
I believe it's on January 8th at 11 AM Pacific.

**Comment by littledan** [comment]
Great, how do I join?

**Comment by iansu** [comment]
There's a calendar of public meetings here: https://calendar.google.com/calendar/embed?src=nodejs.org_nr77ama8p7d7f9ajrpnu506c98%40group.calendar.google.com

That often includes a Zoom link for the meeting. It might also be posted in an issue in this project. At the moment I don't see the meeting on the calendar or anything here so I'm not sure if it's still on for January 8th. cc @boneskull

**Comment by boneskull** [comment]
The meeting is in 10m... it's on the calendar as of late last week.
