### ISSUE TITLE
Add a rule to the Node ESLint plugin to flag packages that are now built in to Node.js

### ISSUE THREAD

**Issue by iansu** [nodejs/tooling#110]
We've started incorporating some third-party packages like `mkdirp` and `rimraf` into Node core. We could add a rule to the Node ESLint plugin that would flag this to users if they're using the package in their code. In some cases the npm packages provide additional functionality, for example `rimraf` also provides binlinks so we probably only want to flag certain usages.

**Comment by ljharb** [comment]
That would be a harmful rule imo, unless the package **explicitly** declares an `engines.node` for which those packages are unnecessary.

**Comment by iansu** [comment]
The ESLint rule could maybe define that? This is a just a placeholder issue that I created during our meeting today. It's certainly not a fully thought out proposal. We did discuss that something like this could have some negative affects as well and we'll be discussing it more in future meetings.

**Comment by ljharb** [comment]
Absolutely it could :-) i just want to caution against anything that could encourage package maintainers to unnecessarily drop support for a platform version, thus cutting off users.

**Comment by iansu** [comment]
Yeah, that's definitely a good perspective. We'll be discussing this more and getting more input from the community before moving ahead with anything.

**Comment by joesepi** [comment]
We've decided (in today's meeting) to close this and open a more generic issue around alerting end users to new features in core when they are using a package/shim/whatever.
