### ISSUE TITLE
Collab Summit Session - Austin June 2022

### ISSUE THREAD

**Issue by iansu** [nodejs/tooling#140]
Should we submit a session to the Collab Summit at OpenJS World? https://github.com/orgs/nodejs/teams/members/discussions/18

**Comment by joesepi** [comment]
Discussed in today's meeting.

Propose two sessions. (Would prefer Thursday)

Session 1 - 2hrs
1. Get new people interested
2. What we've done in the past year
3. Current state of affairs (discuss parseArgs and any other open work)

Session 2 - 2hrs
4. What do we want to do next? (Include discussion of the scope of the work of this group)

**Comment by ruyadorno** [comment]
What about the length? Personally I have the impression that 2h might be a bit too long (specially for `Session 1`) I think it might intimidate some of the newcomers but I may be wrong.

I'm just curious to ask the question and see if anyone else thinks the same.

**Comment by iansu** [comment]
I agree, I think session 1 could be 1 hour.

**Comment by ngfchristian** [comment]
Hi, if I may ask, where is the session taking place?
Thanks.

**Comment by joesepi** [comment]
We have requested to shorten the Part 1 session to 90min and to minimize overlap with the Next-10 session happening that afternoon as well.

@ngfchristian - this is part of the Collab Summit that is happening in coordination with the OpenJSWorld.com event. Collab Summit sessions are on Thursday and Friday, June 9 & 10) in Austin, TX. There may be an option to include virtual participants if people cannot attend in person.

**Comment by joesepi** [comment]
Summit issue:
https://github.com/openjs-foundation/summit/issues/325

Tooling issue:
https://github.com/nodejs/tooling/issues/140

Collab Summit schedule doc:
https://docs.google.com/spreadsheets/d/1WJpK6ZD43GaI-h-HOuHnG0DmQ8orkxFLbYJ_jUiXX54/edit#gid=0

Virtual details:
https://docs.google.com/spreadsheets/d/1rdROZMUuBWFpobbgCuCT8r6h9V5G4shqWt9pLGI3Clg/edit?usp=sharing
