### ISSUE TITLE
Inclusion in WinterCG Runtime Keys Proposal

### ISSUE THREAD

**Issue by Ethan-Arrowood** [nodejs/tooling#166]
Hello! 

Wanted to share that I've published the draft for the runtime-keys proposal. It is heavily inspired by Node's existing usage of the `node` key as documented here: https://nodejs.org/dist/latest-v16.x/docs/api/packages.html#conditional-exports . I've included a section for Node.js in the proposal here: https://github.com/wintercg/runtime-keys/pull/2/files#diff-5e793325cd2bfc452e268a4aa2f02b4024dd9584bd1db3c2595f61f1ecf7b985R76-R84 and would like to get someone from either this working group or the TSC to essentially _sign off_ on it. Let me know if you have any questions or feedback. Please also feel free to get involved in the proposal PR. Thank you!

**Comment by Ethan-Arrowood** [comment]
@nodejs/tooling / @nodejs/tsc bump - want to get someone's sign off here before we proceed with the initial spec. Again, I don't see any conflict but want explicit acknowledgment before proceeding 😄

**Comment by aduh95** [comment]
I've added my 👍 on the linked issue as it looks good to me personally. I've added https://github.com/nodejs/tooling/labels/tsc-agenda label so we can discuss if there's a consensus for signing this off officially.

**Comment by mhdawson** [comment]
Looks fine to me

**Comment by joyeecheung** [comment]
LGTM

**Comment by Ethan-Arrowood** [comment]
Thank you yes this is plenty sufficient for us to proceed. Thank you!

**Comment by Trott** [comment]
> Thank you yes this is plenty sufficient for us to proceed. Thank you!

OK, I'm assuming this can be closed, but if I'm wrong and there's more to do here, by all means, re-open or leave a comment.
