### ISSUE TITLE
Implement shutil in Node.js core

### ISSUE THREAD

**Issue by iansu** [nodejs/tooling#23]
Based on a discussion in the Tooling WG meeting on March 19, 2019 we've decided that the best way forward with rimraf is to implement a new module in Node.js core inspired by shutil from Python: https://docs.python.org/2/library/shutil.html#module-shutil

Eventually we'd like to implement more methods from this module. I've volunteered to do the initial implementation of rimraf.

**Comment by iansu** [comment]
If someone could label this with `tooling-agenda` that would be appreciated. Or better yet give me permission to do so. 😀

**Comment by BridgeAR** [comment]
Is there any status update on this?

**Comment by iansu** [comment]
@BridgeAR I'm planning to submit a PR for this today.

**Comment by iansu** [comment]
Landed in https://github.com/nodejs/node/pull/29168! 🎉
