### ISSUE TITLE
tooling meeting at OpenJS Collab Summit

### ISSUE THREAD

**Issue by boneskull** [nodejs/tooling#29]
I've submitted a request for a timeslot at the [collab summit](https://github.com/nodejs/summit) so we can meet face-to-face if anybody else is going to be there.  Will see if we can stream & videoconference as well.

**Comment by iansu** [comment]
I wish I was going to be there. Hopefully in October, wherever that may be.

**Comment by bcoe** [comment]
:wave: I'll be there with bells on.

**Comment by boneskull** [comment]
minutes are now in the minutes dir
