### ISSUE TITLE
new meeting time needed

### ISSUE THREAD

**Issue by boneskull** [nodejs/tooling#36]
Hi,

We need to choose a new meeting time, because our current one conflicts with half of the  [OpenJS Foundation CPC](/openjs-foundation/cross-project-council) meetings (of which I must be in attendance).

This will also give us a chance to meet every two weeks instead of three, which was forced by a conflict with another recurring Node.js meeting.

Also, @bcoe and/or @iansu should have access to YouTube & Zoom to run the meetings in my absence.  

A suggestion: Fridays at 10 or 11 pacific (or later) work for me.

**Comment by iansu** [comment]
Friday mornings sound good. 11am or 12pm are the best times for me.

**Comment by bcoe** [comment]
10AM PDT works best for me, but I could do 11AM PDT worst case scenario (it just sometimes overlaps with mentorship meetings).

**Comment by iansu** [comment]
I got my timezone math wrong. 🤦‍♂️

10am pacific is actually the best time for me.
