### ISSUE TITLE
agenda for collaborator summit

### ISSUE THREAD

**Issue by boneskull** [nodejs/tooling#4]
* introductions (what developers tools are folks in the room representing?).
* blurb about Node.js' Tooling Group from @boneskull.
* interesting things currently in flight:
  * extended filesystem API (mkdirp, rimraf, readdir).
  * test coverage: https://github.com/nodejs/node/issues/22919
* how should we handle backwards compatibility? polyfills? (@evocateur)
* what other API extensions should we be working on?
* call to action (get more folks to join monthly tooling meetings?).
* group meetings & user feedback sessions
* build tooling for any announcements; see [nodejs/create-node-meeting-artifacts](https://github.com/nodejs/create-node-meeting-artifacts)
* add [execvp](https://linux.die.net/man/3/execvp) functionality (@bengl)
* why does [cross-spawn](https://npm.im/cross-spawn) even need to exist

(@boneskull, @bengl feel free to edit this)

**Comment by mcollina** [comment]
Sure! Would you like to send a PR?

**Comment by bcoe** [comment]
see WIP agenda: https://github.com/nodejs/tooling/issues/5

**Comment by bengl** [comment]
I'd like to have some conversation around adding [`execvp`](https://linux.die.net/man/3/execvp)-esque functionality to Node.js.

**Comment by evocateur** [comment]
It would be interesting to sketch out the back-compat story, if that hasn't already been done elsewhere. (Literal back-ports to older release lines vs userland "ponyfills", etc)

**Comment by ruyadorno** [comment]
looking forwards to this, will def gonna be there 😊

**Comment by bengl** [comment]
Here is the progress I have so far on `execvp`: https://github.com/bengl/node/tree/execvp

I haven't made it into a PR because it's not even close to ready (Windows not working properly, etc.).

**Comment by bcoe** [comment]
here's the cross-library stuff I was talking about: https://github.com/bcoe/awesome-cross-platform-nodejs

**Comment by ErickWendel** [comment]
\o/

**Comment by styfle** [comment]
@bcoe Nice list! I got a Desktop JS List with several cross platform tools https://github.com/styfle/awesome-desktop-js

**Comment by bcoe** [comment]
see: https://github.com/nodejs/tooling/pull/6
