### ISSUE TITLE
Help us pick topics for working group meeting at collaborator summit

### ISSUE THREAD

**Issue by bcoe** [nodejs/tooling#52]
We will be running a meeting at the [OpenJS Collaborator's Summit](https://www.cvent.com/events/node-js-interactive-2019/registration-cd8a157b1e074233a1c5222b6e58dd55.aspx?r=e83a52ea-60e2-4fe1-b594-4a8cc88c55d6&tystub=1hqsfg&fqp=true&_ga=2.103709380.595442722.1575926090-558321044.1569704880&_gac=1.28204110.1573755225.Cj0KCQiAk7TuBRDQARIsAMRrfUZI92DvFSsPTylD5MwDy9MvoPfH-yDfFqdZ4MQEW6SRWR7ocC88V_oaAhbkEALw_wcB).

Help us pick some of the topics for the conversation, by adding an emoji to the comments in this thread.

----

👍= we should discuss this topic.
👎 = I'm not interested in this topic.
_Add a new comment to this thread to suggest a topic._

**Comment by bcoe** [comment]
## Source Maps in Node.js Core

Source map support was recently added to Node.js core, let's discuss the work that remains, and how folks can chip in.

**Comment by bcoe** [comment]
## A Better Argument Parser in Node.js Core

`process.argv` is a hassle for making complex command line programs, should we add an argument parser to core?

**Comment by iansu** [comment]
## A sleep command in Node.js Core

People attempt to implement `sleep` in [many different ways](https://stackoverflow.com/questions/14249506/how-can-i-wait-in-node-js-javascript-l-need-to-pause-for-a-period-of-time/41957152) in Node.js. There are also [several packages](https://www.npmjs.com/search?q=sleep) that implement this functionality. Should we implement a native `sleep` method in Node.js core?

**Comment by boneskull** [comment]
distributing node apps as self-contained binaries 

this would enable an app to be installed and run by a user without having to install a separate node runtime.

**Comment by boneskull** [comment]
execvp support

this a “process replacement” api. tools may find this useful, but no such system api exists on windows (to my knowledge). might need a libuv implementation? cc @ruyadorno

**Comment by iansu** [comment]
## ES module replacement (Hot Module Reloading)

The current ESM loader in Node.js does not allow for loaded modules to be replaced at run time. This prevents implementing things like watch mode in build and test tools. Reference: https://github.com/nodejs/tooling/issues/51
