### ISSUE TITLE
NEW MEETING TIME AGAIN

### ISSUE THREAD

**Issue by boneskull** [nodejs/tooling#55]
as per some discussions at the collab summit, we're going to need to try to find a new meeting time to avoid a major conflict with npm's meetings. (cc @darcyclarke, @ruyadorno)

I'm going to create a Doodle with everyone on this team.  If you would like to be added to the doodle, please respond here with an email address. 

The doodle won't contain times that I'm unavailable, and it can't conflict with other Node.js team meetings.

**Comment by ruyadorno** [comment]
I feel yelled at with that title @boneskull 😳 hehehe

**Comment by boneskull** [comment]
DOODLE LINK for new Node.js Tooling Group meeting (if you didn't get an invite):

https://doodle.com/poll/xnswxspsfm6ztgcb

Apologies for the blast, but want to cast the net wider: cc @nodejs/collaborators

**Comment by boneskull** [comment]
nobody actually responded with an email address, so I took the liberty.

**Comment by boneskull** [comment]
Per the Doodle poll we'll be meeting at 1p every other Friday, starting this week.

**Comment by Trott** [comment]
Should this issue now be closed?

**Comment by boneskull** [comment]
@Trott I GUESS SO

**Comment by ruyadorno** [comment]
THANK YOU CHRIS
