### ISSUE TITLE
Improvements to the fs.promises API

### ISSUE THREAD

**Issue by iansu** [nodejs/tooling#90]
A number of filesystem methods seem to be missing from `fs.promises`. Why is this and is there anything we can do to improve this situation?

**Comment by targos** [comment]
What are the missing methods?

**Comment by ruyadorno** [comment]
I'll close this one for inactivity, feel free to reopen / open a new one (but please be specific about what methods and APIs are missing) in case anyone thinks this is something that still needs improvements. 😊
