### ISSUE TITLE
Recursive copy

### ISSUE THREAD

**Issue by iansu** [nodejs/tooling#98]
Implement a recursive copy command in Node.js. I have been drafting a proposal for this functionality in this document: https://hackmd.io/Q2O7hVyZSKClYW9Vyipeig

At this stage I'd like feedback from the Tooling group on the proposal. Once we're happy with it we can open an issue in the main Node.js repo to get broader feedback. If all goes well we can follow up with an implementation.

**Comment by iansu** [comment]
@RyanZim We're considering using the fs-extra recursive copy implementation in Node.js. I'd love your feedback on this proposal and on incorporating part of fs-extra into Node core. cc @CxRes

**Comment by RyanZim** [comment]
@manidlou is the collaborator that handles most things related to `copy` and `move` in fs-extra; so looping him in here since his feedback is probably most useful here.

Would you be planning on implementing the `filter` option as well?

**Comment by CxRes** [comment]
I am not involved with `fs-extra` though I use it in my work. And, I find the `copy` function incredibly useful.

However, from the point of view of nodejs, I think the `copy` function as implemented in `fs-extra` is limited. Don't get me wrong, it is really good for day to day use, its just that recursive copy is a relatively complex operation.

I would suggest that you consider [`cp`](https://ss64.com/bash/cp.html), [`rsync`](https://ss64.com/bash/rsync.html) and Windows [Robocopy](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/robocopy) for inspiration.

A few things, I would like are: 
+ A verbose output as a return value
+ A filter that can take regex and/or glob array (most times I end up importing `picomatch`)

Perhaps later you can add:
+ Preserve attributes, permissions and time-stamps
+ interactive mode

**Comment by manidlou** [comment]
@iansu I just want to remind you that our copy implementation in `fs-extra` is a bit different than unix `cp` command. For instance, in `fs-extra`, when copying a file, the user requires to explicitly specify the destination file name which is different than the implementation of unix `cp` command.
